<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA5bXTGy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA5bXTGy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA5bXTGy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA5bXTGy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerA5bXTGy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'A5bXTGy',
    'container.build_id' => '93fbb7c3',
    'container.build_time' => 1668355985,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA5bXTGy');
