<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3CQx5x6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3CQx5x6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3CQx5x6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3CQx5x6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3CQx5x6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3CQx5x6',
    'container.build_id' => '94878647',
    'container.build_time' => 1668443033,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3CQx5x6');
